### ISSUE TITLE
[BUG] Custom trades do not show in JEI on servers, UNLESS you try in sp first?

### ISSUE THREAD

**Issue by aaronhowser1** [SpaceCat97/CustomVillagerTrades#2]
**Describe the bug**
On servers, you cannot see custom trades in JEI. You can on singleplayer.

Singleplayer:
![image](https://user-images.githubusercontent.com/15698722/188400287-12af7c79-1862-4165-b40f-de6a2d17dc43.png)

Server:
![image](https://user-images.githubusercontent.com/15698722/188401675-e727e19d-8385-469e-8b5c-a26aa2ff7d49.png)

The trades DO work, I just can't see them in JEI.
![image](https://user-images.githubusercontent.com/15698722/188401877-0104511a-0918-4dcf-97d7-5e2c9d9bfea4.png)
![image](https://user-images.githubusercontent.com/15698722/188402037-484ccc86-fd78-49b3-a44d-34c87947c9b7.png)

Weirdly, and I didn't know this until I was getting the singleplayer image, if I go into SP and then return to the server, I *can* see everything.

**Versions**
- Minecraft: 1.18.2 
- Forge: 40.1.68
- Mod: customvillagertrades-1.18.2_V17

**Comment by SpaceCat97** [comment]
This is because there is no direct integration with JEI. The trades are not static so it has the capability to be different across different servers, it looks like JEI does not detect these by default and requires developers to add direct integrations.

1.18 is planned to be unsupported soon, so there won't be a fix for this version. I may include a fix for it in the latest version when it is released.
